# Site settings
title: Dualluck's Blog
header-img: img/home-bg.jpg
email: 122539137@qq.com
copyright_name: dualluck
description: "test github pages at first!"
baseurl: "/"
url: "https://dualluck.github.io"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  StartBootstrap
email_username:  122539137@qq.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]